export class Fornecedores {
    CodigoFornecedor: number;    
    FornecedorSituacao: string;
    CodigoFornecedorSituacao: number;
    CodigoFornecedorTipo: number;
    FornecedorTipo: any [];  
    CodigoUnidade: number;
    Unidades: any [];  
    DtCadastro: Date;
    NomeSocial: string;
    NomeFantasia: string;
    CnpjCpf: string;
    IE: string;
    RgResponsavel: string;
    RgRespOrgaoEmissor: string;
    RgRespOrgaoUFCodigoBaseUF: number;
    RgRespDtEmissao: string;
    CpfRespEmpresa: string;
    CpfRespf: string;
    CpfRespUnidade: string;
    NomeResponsavel: string;
    Telefone: string;
    Celular: string;
    Email: string;
    EnderecoRua: string;
    EnderecoNumero: string;
    Bairro: string;
    Cidade: string;
    Cep: string;
    CodigoBaseUF: number;
    Municipios: any [];  
    UFs: any [];  
    CpfCnpjEmpresa: string;         
    Unidade:string;
    CodigoBaseMunicipio: number;    
    RecordCount: number;
    RowsPage: number;
    PageNumber: number;
    Thumbnail: string;
    VwThumbnail: string;
}
