export const environment = {
  production: true,
  AppName     : 'Woppa',
  AppNameSigla: 'Woppa',
  AppVersion  : 'Versão 1.0.1',
  AppEmailSuporte: 'wearplace@gmail.com.br',
  AppWhatAppSuporte: 'https://wa.me/5561982049030',
  logoCliente : '/assets/app/logo/LgWearPlace.jpg',
  logoApp     : '/assets/app/logo/logo.png',
  login__image:  '/assets/app/img/pesos.png', 
  iconAvatarUsuarioDefault : '/assets/app/imgs/userPhoto.svg',
  gifLoadPhoto : '/assets/app/imgs/loadphoto.gif',
  pathPdfs: '/assets/pdfs/',
  pathMedias: '/medias/',
  lgplay:  '/assets/app/logo/IconeWoppa512x.png',     
  poster:  '/assets/app/logo/IconeWoppa512x.png',  
  thumbNailNewVideo: '/assets/app/imgs/tumbnailNewVideo.jpg',   
  subtitle: { br:'/assets/app/subs/MVI_2223-pt-br.vtt',  
              us: '/assets/app/subs/MVI_2223-us.vtt',  
              es: '/assets/app/subs/MVI_2223-es.vtt'},
   videos: {  mp4:'/assets/app/videos/MVI_2223.mp4',    
              ogg: '/assets/app/videos/videogular.ogg',  
              webm: '/assets/videos/videogular.webm',
              path: '/assets/videos/',
              
              }
};
